### ISSUE TITLE
Фидбек

### ISSUE THREAD

**Issue by shafua** [DXLETED/lambdabird-test#1]
- Мьютиться массив `data` из `useState`
- Билд директорию (в данном случае `static`) тоже нужно помещать в gitignore
- `dev`  и `build` не создают css в `/static`

_Дополнительные замечания_

- Не помешал бы prettier или хотя бы eslint — строки в 100500 символов не поддаются прочтению; в JSX, если пропсов много (>1), каждый пропс пишется с новой строки
- Если открыть таблицу с реальными результатами соревнований то можно обнаружить что формат результата стрельбы отображается не просто как количество попаданий — это пример неявного требования (такого, которое явным образом не описано в ТЗ, но подразумевается заказчиком).
- Колонки задаются индексом

**Дополнительные плюсы**

- бекенд
- разбитие на компоненты

Тестовое засчитывается. Второе тестовое отправим в ближайшее время на email.

**Comment by DXLETED** [comment]
Исправил
